In [1]:
import numpy as np

In [2]:
def f(x:np.array)->float:
    return (1/ 2) * (x[0] - 2) **2 + (x[1] -1) ** 2

In [3]:
def grad_f(x:np.array)->float:
    return np.array([x[0] - 2, 2 * (x[1] - 1)])

In [4]:
-(1) * grad_f([2, 1])

array([0, 0])

In [5]:
def busca_linear_inexata(f, grad_f, x_0)-> np.array:
    eta = 1e-2

    d = lambda x: (-1) * grad_f(x)

   

    x_t = x_0

    while (np.linalg.norm(grad_f(x_t)) > 1e-4):
        print(np.linalg.norm(x_t))

        t = 1

        while (f(x_t + t * d(x_t)) > f(x_t) + eta*t * np.inner(grad_f(x_t), d(x_t))):
            t /=2
    
        x_t = x_t + t * d(x_t)


    return x_t

In [6]:
busca_linear_inexata(f, grad_f, np.array([2000, 3400]))

3944.616584663204
3398.0005885814676


array([2., 1.])

In [7]:
def f_2(x):
    return x[0] ** 2 + x[0] * x[1] + x[1]**2

In [8]:
def grad_f_2(x):
    return np.array([2* x[0] + x[1], x[0] + 2*x[1]])

In [9]:
busca_linear_inexata(f_2, grad_f_2, np.array([2, 3]))

3.605551275463989
1.8027756377319946
0.9013878188659973
0.45069390943299864
0.22534695471649932
0.11267347735824966
0.05633673867912483
0.028168369339562415
0.014084184669781208
0.007042092334890604
0.003521046167445302
0.001760523083722651
0.0008802615418613255
0.00044013077093066273
0.00022006538546533137
0.00011003269273266568
5.501634636633284e-05


array([-2.28881836e-05, -1.52587891e-05])

In [10]:
def h(x): # função de entropia negativa
    n = len(x)
    sum_ = 0

    for i in range(n):
        sum_ += x[i] * np.log(x[i]) - x[i]

    return  sum_

In [11]:
def grad_h(x): # gradiente da entropia negativa (vetor de ln(x_i))
    return np.log(x)

In [12]:
def inv_grad_h(x): # inversa do gradiente da entropia negativa
    return np.exp(x)

In [13]:
def h_2(x): 
    return (1/2) * np.linalg.norm(x) ** 2

In [14]:
def grad_h_2(x):
    return x

In [15]:
def inv_grad_h_2(x):
    return x

In [39]:
def gradiente_espelho(f, grad_f, inv_grad_h, grad_h, x0):

    xt = x0

    eta = 1e-1

    while (np.linalg.norm(grad_f(xt)) > 1e-8):

        xt = inv_grad_h(grad_h(xt) - eta * grad_f(xt))
    
    return xt

In [41]:
gradiente_espelho(f, grad_f, inv_grad_h, grad_h, np.array([200, 30]))

array([1.99999999, 1.        ])