In [57]:
import numpy as np
from scipy.sparse import rand
from scipy.optimize import lsq_linear
from read_instance import *
from mirror_gradient_descent import *

rng = np.random.default_rng()
n = 10000
A = rand(n, n, density=1e-4, random_state=rng)
b = rng.standard_normal(n)
b[b<0] = -b[b<0]

In [58]:
res = lsq_linear(A, b, lsmr_tol='auto', verbose=1)

The unconstrained solution is optimal.
Final cost 2.0324e+03, first-order optimality 6.19e-05


In [59]:
A.row

array([8846, 8333,  821, ..., 2210, 9468, 4160])

In [60]:
A.col

array([4134,  212, 5554, ..., 4499,  890,  932])

In [61]:
A.data

array([0.86871664, 0.57982182, 0.54709305, ..., 0.09190783, 0.47837172,
       0.99513468])

In [62]:
def f(x:np.array):
    return (1/2) * np.linalg.norm(A @ x - b)**2

In [63]:
def grad_f(x:np.array):
    return A.T @ (A @ x -b)

In [64]:
p = 2
inv_p = lambda x: inv_grad_norma_p(x, p)
grad_p = lambda x: grad_norma_p(x, p)

In [ ]:
x_star = mirror_gradient(grad_f, inv_p, grad_p, np.zeros(A.shape[1]), epsilon= 1e-4, eta = 1e-1)

58.87319868376449
50.742183471593215
44.46491965439893
39.5010607351612
35.49295045230539
32.19787311893603
29.446931773933887
27.119706410419447
25.128355221026517
23.40743949419858
21.90727246216339
20.589476959692348
19.423954689297744
18.3867759764046
17.458682012636007
16.62400274804092
15.86986219607064
15.185586006852935
14.562253730143109
13.99235614887108
13.469529976269095
12.988350246939182
12.544166243377946
12.132970635557593
11.751294218569841
11.396120568722324
11.06481633837093
10.755073933437007
10.464864073745867
10.192396300264985
9.936085917689418
9.694526182902125
9.466464796289287
9.250783942957773
9.046483278594287
8.852665370307628
8.66852319391507
8.49332936144078
8.326426810344213
8.167220732405813
8.015171557713552
7.869788839691242
7.730625912033098
7.597275208880093
7.469364156466906
7.346551558471485
7.22852440895517
7.114995076521539
7.005698811491524
6.9003915347677305
6.798847872866019
6.700859408508862
6.606233120350588
6.5147899889606276
6.42636374922

In [69]:
f(x_star)

2050.6556764566926