In [1]:
from read_instance import *
from mirror_gradient_descent import *

In [2]:
mi = 100
t0 = 0.1

In [3]:
c, A, b = read_instance('vetores_formato.txt')

[  0   0   0 ... 818 819 819]
[605 606 607 ...  47  51  52]
[1. 1. 1. ... 1. 1. 1.]
5076


In [4]:
def f(x):
    return c.T @ x + (mi / 2) * (np.linalg.norm(A @ x - b)) ** 2

In [5]:
def grad_f(x):
    
    return c + (mi * A.T @ (A @ x - b))

In [6]:
x_star = mirror_gradient(f, grad_f, inv_grad_h, grad_h, np.full(A.shape[1], 100))

[101.00501671   0.         101.00501671 ...   0.           0.
   0.        ]
[102.020134   0.       102.020134 ...   0.         0.         0.      ]


c:\Users\JoãoPereira\OneDrive - bitkalabs.com.br\Desktop\Gradiente_espelho\mirror_gradient_descent.py:17: RuntimeWarning: overflow encountered in exp
  return np.exp(x)
c:\Users\JoãoPereira\OneDrive - bitkalabs.com.br\Desktop\Gradiente_espelho\mirror_gradient_descent.py:14: RuntimeWarning: divide by zero encountered in log
  return np.log(x)
c:\Users\JoãoPereira\OneDrive - bitkalabs.com.br\Desktop\Gradiente_espelho\mirror_gradient_descent.py:37: RuntimeWarning: invalid value encountered in subtract
  xt = inv_grad_h(grad_h(xt) - eta * grad_f(xt))


In [10]:
x_star[x_star>0]

array([1.02020134e+002, 1.02020134e+002, 1.02020134e+002, 1.02020134e+002,
       9.60789439e+001, 9.60789439e+001, 1.00000000e+002, 6.31283646e+001,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf,             inf,
                   inf,             inf,             inf, 8.86920437e+001,
       1.19721736e+002, 4.05519997e+002, 9.48589711e-172, 1.04645762e-094,
       1.00000000e+002, 1.00000000e+002])

In [8]:
np.inner(c, x_star)

nan